import DatabaseService from './src/main/ets/service/DatabaseService'

export { PermissionsUtil } from './src/main/ets/utils/PermissionsUtil'
export { PreferenceUtil } from './src/main/ets/utils/PreferenceUtil'
export { LoginUtil,LoginInfo } from './src/main/ets/utils/LoginUtil'
export { Logger } from './src/main/ets/utils/Logger'
export * from './src/main/ets/utils/MathUtil'
export { OrderType } from './src/main/ets/model/OrderType'
console.log('DatabaseService:', DatabaseService);
export default DatabaseService;

